export const AVAILABLE_ROLES = [
  {
    id: 1,
    name: "Sales Manager",
    description: "Manages sales operations",
    duties: [1, 2],
    entities: ["Customer"],
    privileges: [
      "Customer_Basic_Access",
      "Customer_Advanced_Edit",
      "Sales_Order_Create",
      "Sales_Order_Edit",
    ],
    privilegeCount: 4,
  },
  {
    id: 2,
    name: "Account Manager",
    description: "Manages customer accounts",
    duties: [1],
    entities: ["Customer"],
    privileges: ["Customer_Basic_Access", "Customer_Advanced_Edit"],
    privilegeCount: 2,
  },
  {
    id: 3,
    name: "Operations Manager",
    description: "Manages warehouse operations",
    duties: [3],
    entities: ["Spare Part"],
    privileges: ["Inventory_View", "Inventory_Edit", "Stock_Adjustment"],
    privilegeCount: 3,
  },
  {
    id: 4,
    name: "Finance Officer",
    description: "Manages financial operations",
    duties: [4],
    entities: ["Spare Part"],
    privileges: ["Purchase_Order_Create", "Purchase_Order_Edit"],
    privilegeCount: 2,
  },
  {
    id: 5,
    name: "System Administrator",
    description: "Manages system configuration",
    duties: [1, 3],
    entities: ["Customer", "Spare Part"],
    privileges: ["Customer_Basic_Access", "Inventory_View", "Inventory_Edit"],
    privilegeCount: 3,
  },
];
